// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTwwgfn3hwmRr61df7AeE_McElAiY3mfE',
    appId: '1:206349483190:web:75ff14ffe744f70f1d7a17',
    messagingSenderId: '206349483190',
    projectId: 'smartglasstcc',
    authDomain: 'smartglasstcc.firebaseapp.com',
    storageBucket: 'smartglasstcc.appspot.com',
    measurementId: 'G-ZBH3HLZ0YT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3LaRZMpUUV3qveiYKWz5OHjRmrwez-J4',
    appId: '1:206349483190:android:647a3824c8de61f61d7a17',
    messagingSenderId: '206349483190',
    projectId: 'smartglasstcc',
    storageBucket: 'smartglasstcc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFHAd0bVRDiH_EKXdjPB8_6g0EImzUpUs',
    appId: '1:206349483190:ios:468846ccbd8483f31d7a17',
    messagingSenderId: '206349483190',
    projectId: 'smartglasstcc',
    storageBucket: 'smartglasstcc.appspot.com',
    iosClientId: '206349483190-e4cimloghj0j6suv8u1p0b33nnl1m8mn.apps.googleusercontent.com',
    iosBundleId: 'com.example.testeAppTcc',
  );
}
