// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNsx-i3eccTRCE0eI37tf77NhyNBHX170',
    appId: '1:465617825666:web:382be2387d98ebc072299b',
    messagingSenderId: '465617825666',
    projectId: 'flutterappzanini',
    authDomain: 'flutterappzanini.firebaseapp.com',
    storageBucket: 'flutterappzanini.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTu_KCrSe8gHGX16YsAWfAMgnRVCg_kcI',
    appId: '1:465617825666:android:2eb3b6b819183bdc72299b',
    messagingSenderId: '465617825666',
    projectId: 'flutterappzanini',
    storageBucket: 'flutterappzanini.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHOacZmCugNsLz0akO5StM2FUXENcJR18',
    appId: '1:465617825666:ios:2bf3bed434f06c4c72299b',
    messagingSenderId: '465617825666',
    projectId: 'flutterappzanini',
    storageBucket: 'flutterappzanini.appspot.com',
    iosClientId: '465617825666-2ir3f4pg39r79pn59ifdtrpg85nbtcq8.apps.googleusercontent.com',
    iosBundleId: 'com.example.appOculosZan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHOacZmCugNsLz0akO5StM2FUXENcJR18',
    appId: '1:465617825666:ios:2bf3bed434f06c4c72299b',
    messagingSenderId: '465617825666',
    projectId: 'flutterappzanini',
    storageBucket: 'flutterappzanini.appspot.com',
    iosClientId: '465617825666-2ir3f4pg39r79pn59ifdtrpg85nbtcq8.apps.googleusercontent.com',
    iosBundleId: 'com.example.appOculosZan',
  );
}
